version: '3.7'
services:
  mysql:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    restart: on-failure
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql:rw
      - ./config/my.cnf:/etc/mysql/my.cnf:rw
    image: xin8docker/mysql
    ports:
      - 3306:3306
    networks:
      - framework-net

networks:
  framework-net:
    external: true