FROM mysql:8.0.17

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' > /etc/timezone \
    && rm -rf /etc/mysql/my.cnf

COPY ./0flush_privileges.sql /docker-entrypoint-initdb.d

COPY ./8slow_log_setting.sql /docker-entrypoint-initdb.d